# Arquivo de configuração para o serviço de Static Site no Render.
# https://render.com/docs/blueprint-spec

services:
  # Define um serviço do tipo Static Site (Site Estático)
  - type: static_site # CORREÇÃO: O tipo correto é 'static_site'
    # Nome do seu serviço no painel do Render. Pode ser o que você quiser.
    name: portfolio-clenio
    # O diretório que contém os arquivos a serem publicados.
    # Como seu index.html está na raiz, usamos '.'
    publishDir: .
    
    # --- IMPORTANTE SOBRE AS CHAVES DE API ---
    # Para um site estático, as chaves no seu arquivo 'config.js'
    # serão usadas diretamente no lado do cliente.
    # O arquivo '.gitignore' que criamos é a medida de segurança
    # ESSENCIAL para garantir que o 'config.js' NUNCA seja
    # enviado para o seu repositório no GitHub.
    
    # O Render detectará automaticamente as mudanças no seu repositório
    # do GitHub (ramo main) e fará o deploy do seu site.
